#!/usr/bin/env python3
#
# REST API Client & Server Launcher
#
# To learn this CLI try:
#   ./helloworld -h
#   ./helloworld start -h
#   ./helloworld get -h
#
from sys import exit, stderr
from os import getpid
from argparse import ArgumentParser
from json import dumps

from app import app, create_app, init_app
from restc import rest_client


def cli_stub( options ):
    '''
    Called when user executes ./helloworld
    '''
    ap.print_help()
    return

def cli_start( options ):
    '''
    Launch REST API development server.
    Called when user executes, e.g.
    ./helloworld -c helloworld.cfg start
    '''

    print('Starting service pid', str(getpid()))
    app = create_app(options.config)
    iface = app.config.get('SERVICE_IF', '0.0.0.0')
    port = int(app.config.get('SERVICE_PORT', 44444))

    init_app(app)
    try:
        app.run(
            host=iface, 
            port=port, 
            threaded=True,
            processes=1 )

    except KeyboardInterrupt:
        print( 'Ctrl-C caught in service start, aborting.', file=stderr )

    except Exception as e:
        print( 'Failed to start the service:', str(e), file=stderr )

    exit( 1 )
    return

def cli_get( options ):
    '''
    REST API client.
    Performs HTTP GET
    '''

    app = create_app(options.config)
    iface = app.config.get('SERVICE_IF')
    port = app.config.get('SERVICE_PORT')
    cl = rest_client(iface, port, options.verbose)
    try:
        for uri in options.uri:
            (status_code, rdata) = cl.get(uri)
            #print('HTTP status code:', status_code)
            print('got back:', dumps(rdata, indent=4))

    except Exception as ex:
        print('Connection failed: ', str(ex), file=stderr)

    return

#
# argument parser
#
ap = ArgumentParser( 
    'helloworld',
    description= 'HelloWorld REST API server.')
ap.add_argument(
    '-c',
    '--config',
    default='helloworld.cfg',
    help = 'Load configuration from CONFIG, defaults to helloworld.cfg')
ap.add_argument(
    '-v',
    '--verbose',
    action='store_true',
    default=False,
    help = 'Tell more about what is going on')
ap.set_defaults( func = cli_stub )

# start adding sub-commands
scp = ap.add_subparsers( help = 'HelloWorld sub-commands' )

# start server sub-command
scp_start = scp.add_parser(
    'start',
    description = 'Start the REST API development server.',
    help = 'Start the REST API development server.  Not for production use. ' )

scp_start.set_defaults( func = cli_start )

# get sub-command
scp_get = scp.add_parser(
    'get',
    description = 'Issue HTTP GET to the REST API server.',
    help = 'Issue GET request to the REST API server. ' )
scp_get.add_argument('uri', nargs='+')
scp_get.set_defaults( func = cli_get )

# finally, parse the command line
pargs = ap.parse_args()
try:
    pargs.func( pargs )
except KeyboardInterrupt:
    exit( 'Ctrl-C caught, aborting.' )